--!strict
-- Last updated: 25.08.2026
-- Luau type definitions for the Obsidian UI Library

--// Helper & Configuration Types
export type Scheme = {
    BackgroundColor: Color3,
    MainColor: Color3,
    AccentColor: Color3,
    OutlineColor: Color3,
    FontColor: Color3,
    Font: Font,
    RedColor: Color3,
    DestructiveColor: Color3,
    DarkColor: Color3,
    WhiteColor: Color3,
    BackgroundImage: string,
}

export type Icon = {
    Url: string,
    ImageRectOffset: Vector2,
    ImageRectSize: Vector2,
}

export type ContextMenu = {
    Active: boolean,
    Holder: GuiObject,
    Menu: GuiObject,
    List: UIListLayout?,
    Signal: RBXScriptConnection?,
    Size: UDim2 | () -> UDim2,

    Open: (self: ContextMenu) -> (),
    Close: (self: ContextMenu) -> (),
    Toggle: (self: ContextMenu) -> (),
    SetSize: (self: ContextMenu, Size: UDim2 | () -> UDim2) -> (),
}

export type Tooltip = {
    Disabled: boolean,
    Hovering: boolean,
    Signals: { [number]: RBXScriptConnection },
    Destroy: (self: Tooltip) -> (),
}

export type Notification = {
    Title: string?,
    Description: string,
    Time: number | Instance,
    SoundId: string | number?,
    Volume: number?,
    Steps: number?,
    Persist: boolean?,
    Icon: string?,
    BigIcon: string?,
    IconColor: Color3 | string?,
    TitleColor: Color3?,
    DescriptionColor: Color3?,
    Destroyed: boolean,
    PositionInitialized: boolean?,

    Resize: (self: Notification) -> (),
    ChangeTitle: (self: Notification, Text: string) -> (),
    ChangeDescription: (self: Notification, Text: string) -> (),
    ChangeStep: (self: Notification, NewStep: number) -> (),
    Destroy: (self: Notification) -> (),
}

export type KeybindToggle = {
    Normal: boolean,
    Holder: TextButton,
    Label: TextLabel,
    Checkbox: Frame,
    Loaded: boolean,

    Display: (self: KeybindToggle, State: boolean) -> (),
    SetText: (self: KeybindToggle, Text: string) -> (),
    SetVisibility: (self: KeybindToggle, Visibility: boolean) -> (),
    SetNormal: (self: KeybindToggle, Normal: boolean) -> (),
}

export type DraggableLabel = {
    Label: TextLabel,
    SetText: (self: DraggableLabel, Text: string) -> (),
    SetVisible: (self: DraggableLabel, Visible: boolean) -> (),
    SetIcon: (self: DraggableLabel, Icon: string) -> (),
    SetIconPosition: (self: DraggableLabel, Position: string) -> (),
}

export type DraggableButton = {
    Button: TextButton,
    SetText: (self: DraggableButton, Text: string) -> (),
    SetIcon: (self: DraggableButton, Icon: string) -> (),
    SetIconPosition: (self: DraggableButton, Position: string) -> (),
}

export type DraggableImageButton = {
    Button: TextButton,
    SetIcon: (self: DraggableImageButton, Icon: string) -> (),
    SetIconSize: (self: DraggableImageButton, Size: number) -> (),
}

--// Element Creation Info Types
export type ButtonInfo = {
    Text: string,
    Func: (FromKeyPicker: boolean?) -> (),
    DoubleClick: boolean?,
    Icon: string?,
    Tooltip: string?,
    DisabledTooltip: string?,
    Risky: boolean?,
    Disabled: boolean?,
    Visible: boolean?,
}

export type ToggleInfo = {
    Text: string,
    Default: boolean?,
    Callback: ((boolean) -> ())?,
    Changed: ((boolean) -> ())?,
    Tooltip: string?,
    DisabledTooltip: string?,
    Risky: boolean?,
    Disabled: boolean?,
    Visible: boolean?,
}

export type InputInfo = {
    Text: string,
    Default: string?,
    Finished: boolean?,
    Numeric: boolean?,
    ClearTextOnFocus: boolean?,
    Placeholder: string?,
    AllowEmpty: boolean?,
    EmptyReset: string?,
    MaxLength: number?,
    Tooltip: string?,
    DisabledTooltip: string?,
    Callback: ((string) -> ())?,
    Changed: ((string) -> ())?,
    Disabled: boolean?,
    Visible: boolean?,
}

export type SliderInfo = {
    Text: string,
    Default: number?,
    Min: number?,
    Max: number?,
    Rounding: number?,
    Prefix: string?,
    Suffix: string?,
    Compact: boolean?,
    HideMax: boolean?,
    FormatDisplayValue: ((Slider, number) -> string)?,
    Tooltip: string?,
    DisabledTooltip: string?,
    Callback: ((number) -> ())?,
    Changed: ((number) -> ())?,
    Disabled: boolean?,
    Visible: boolean?,
    AllowRightClickInput: boolean?,
}

export type DropdownInfo = {
    Text: string?,
    Values: { [any]: any },
    Default: any,
    DisabledValues: { any }?,
    ValueImages: { [any]: string }?,
    Multi: boolean?,
    DragSelect: boolean?,
    MaxVisibleDropdownItems: number?,
    KeepDisabledValuePosition: boolean?,
    SpecialType: "Player" | "Team"?,
    ExcludeLocalPlayer: boolean?,
    EnablePlayerImages: boolean?,
    AllowNull: boolean?,
    Searchable: boolean?,
    FormatDisplayValue: ((any) -> string)?,
    FormatListValue: ((any) -> string)?,
    Tooltip: string?,
    DisabledTooltip: string?,
    Callback: ((any) -> ())?,
    Changed: ((any) -> ())?,
    Disabled: boolean?,
    Visible: boolean?,
}

export type ViewportInfo = {
    Object: BasePart | Model,
    Camera: Camera?,
    Clone: boolean?,
    AutoFocus: boolean?,
    Interactive: boolean?,
    Height: number?,
    Visible: boolean?,
}

export type ImageInfo = {
    Image: string,
    Transparency: number?,
    Color: Color3?,
    RectOffset: Vector2?,
    RectSize: Vector2?,
    ScaleType: Enum.ScaleType?,
    Height: number?,
    Visible: boolean?,
}

export type VideoInfo = {
    Video: string,
    Looped: boolean?,
    Playing: boolean?,
    Volume: number?,
    Height: number?,
    Visible: boolean?,
}

export type UIPassthroughInfo = {
    Instance: GuiBase2d,
    Height: number?,
    Visible: boolean?,
}

export type KeyPickerInfo = {
    Text: string,
    Default: string?,
    Mode: "Always" | "Toggle" | "Hold" | "Press"?,
    Modes: { "Always" | "Toggle" | "Hold" | "Press" }?,
    SyncToggleState: boolean?,
    NoUI: boolean?,
    WaitForCallback: boolean?,
    Callback: ((boolean) -> ())?,
    ChangedCallback: ((Enum.KeyCode | Enum.UserInputType) -> ())?,
    Changed: ((Enum.KeyCode | Enum.UserInputType) -> ())?,
    Clicked: (() -> ())?,
}

export type ColorPickerInfo = {
    Default: Color3?,
    Transparency: number?,
    Title: string?,
    Resizable: boolean?,
    Callback: ((Color3) -> ())?,
    Changed: ((Color3) -> ())?,
}

export type LoadingInfo = {
    Title: string?,
    Icon: string | number?,
    IconSize: UDim2?,
    LoadingIcon: string | number?,
    LoadingIconColor: Color3?,
    LoadingIconTweenTime: number?,
    CurrentStep: number?,
    TotalSteps: number?,
    ShowSidebar: boolean?,
    AutoResizeHeight: boolean?,
    AlwaysOnTop: boolean?,
    WindowWidth: number?,
    WindowHeight: number?,
    ContentWidth: number?,
    SidebarWidth: number?,
}

--// Addon Types
export type KeyPicker = {
    Text: string,
    Value: string,
    Toggled: boolean,
    Mode: "Always" | "Toggle" | "Hold" | "Press",
    SyncToggleState: boolean,
    Callback: (Toggled: boolean) -> (),
    ChangedCallback: (Key: Enum.KeyCode | Enum.UserInputType) -> (),
    Changed: (Key: Enum.KeyCode | Enum.UserInputType) -> (),
    Clicked: () -> (),
    Type: "KeyPicker",
    Menu: ContextMenu,
    MenuVisible: boolean,

    Display: (self: KeyPicker) -> (),
    Update: (self: KeyPicker) -> (),
    GetState: (self: KeyPicker) -> boolean,
    OnChanged: (self: KeyPicker, Func: (Key: Enum.KeyCode | Enum.UserInputType) -> ()) -> (),
    OnClick: (self: KeyPicker, Func: () -> ()) -> (),
    DoClick: (self: KeyPicker) -> (),
    SetValue: (self: KeyPicker, Data: { string }) -> (),
    SetText: (self: KeyPicker, Text: string) -> (),
    SetMenuVisibility: (self: KeyPicker, Visible: boolean) -> (),
    Destroy: (self: KeyPicker) -> (),
}

export type ColorPicker = {
    Value: Color3,
    Transparency: number,
    Title: string?,
    Callback: (Value: Color3) -> (),
    Changed: (Value: Color3) -> (),
    Type: "ColorPicker",
    Hue: number,
    Sat: number,
    Vib: number,
    ColorMenu: ContextMenu,
    ContextMenu: ContextMenu,

    SetHSVFromRGB: (self: ColorPicker, Color: Color3) -> (),
    Display: (self: ColorPicker) -> (),
    Update: (self: ColorPicker) -> (),
    OnChanged: (self: ColorPicker, Func: (Value: Color3) -> ()) -> (),
    SetValue: (self: ColorPicker, HSV: { number }, Transparency: number?) -> (),
    SetValueRGB: (self: ColorPicker, Color: Color3, Transparency: number?) -> (),
    Destroy: (self: ColorPicker) -> (),
}

export type Addon = KeyPicker | ColorPicker

--// Base Element Types
export type Label = {
    Text: string,
    DoesWrap: boolean,
    Addons: { [number]: Addon },
    Visible: boolean,
    Type: "Label",
    TextLabel: TextLabel,
    Container: GuiObject,
    Holder: TextLabel,
    Parent: BaseGroupbox,

    SetVisible: (self: Label, Visible: boolean) -> (),
    SetText: (self: Label, Text: string) -> (),

    -- From BaseAddons
    AddKeyPicker: (self: Label, Idx: string, Info: KeyPickerInfo) -> Label,
    AddColorPicker: (self: Label, Idx: string, Info: ColorPickerInfo) -> Label,
    Destroy: (self: Label) -> (),
}

export type Button = {
    Text: string,
    Func: (FromKeyPicker: boolean?) -> (),
    DoubleClick: boolean?,
    Icon: string?,
    Tooltip: string?,
    DisabledTooltip: string?,
    TooltipTable: Tooltip?,
    Risky: boolean,
    Disabled: boolean,
    Visible: boolean,
    Tween: Tween?,
    Type: "Button",
    Base: TextButton,
    Stroke: UIStroke,
    Label: TextLabel,
    IconImage: ImageLabel?,
    Holder: Frame,
    SubButton: SubButton?,
    Parent: BaseGroupbox,

    AddButton: (self: Button, Info: ButtonInfo | string, Func: (() -> ())?, Idx: string?) -> SubButton,
    UpdateColors: (self: Button) -> (),
    SetDisabled: (self: Button, Disabled: boolean) -> (),
    SetVisible: (self: Button, Visible: boolean) -> (),
    SetText: (self: Button, Text: string) -> (),
    SetIcon: (self: Button, Icon: string?) -> (),
    Destroy: (self: Button) -> (),
}

export type SubButton = {
    Text: string,
    Func: (FromKeyPicker: boolean?) -> (),
    DoubleClick: boolean?,
    Icon: string?,
    Tooltip: string?,
    DisabledTooltip: string?,
    TooltipTable: Tooltip?,
    Risky: boolean,
    Disabled: boolean,
    Visible: boolean,
    Tween: Tween?,
    Type: "SubButton",
    Base: TextButton,
    Stroke: UIStroke,
    Label: TextLabel,
    IconImage: ImageLabel?,

    UpdateColors: (self: SubButton) -> (),
    SetDisabled: (self: SubButton, Disabled: boolean) -> (),
    SetVisible: (self: SubButton, Visible: boolean) -> (),
    SetText: (self: SubButton, Text: string) -> (),
    SetIcon: (self: SubButton, Icon: string?) -> (),
    Destroy: (self: SubButton) -> (),
}

export type Toggle = {
    Text: string,
    Value: boolean,
    Tooltip: string?,
    DisabledTooltip: string?,
    TooltipTable: Tooltip?,
    Callback: (Value: boolean) -> (),
    Changed: (Value: boolean) -> (),
    Risky: boolean,
    Disabled: boolean,
    Visible: boolean,
    Addons: { [number]: Addon },
    Type: "Toggle",
    TextLabel: TextLabel,
    Container: GuiObject,
    Holder: TextButton,
    Parent: BaseGroupbox,

    UpdateColors: (self: Toggle) -> (),
    Display: (self: Toggle) -> (),
    OnChanged: (self: Toggle, Func: (Value: boolean) -> ()) -> (),
    SetValue: (self: Toggle, Value: boolean) -> (),
    SetDisabled: (self: Toggle, Disabled: boolean) -> (),
    SetVisible: (self: Toggle, Visible: boolean) -> (),
    SetText: (self: Toggle, Text: string) -> (),

    -- From BaseAddons
    AddKeyPicker: (self: Toggle, Idx: string, Info: KeyPickerInfo) -> Toggle,
    AddColorPicker: (self: Toggle, Idx: string, Info: ColorPickerInfo) -> Toggle,
    Destroy: (self: Toggle) -> (),
}

export type Input = {
    Text: string,
    Value: string,
    Finished: boolean,
    Numeric: boolean,
    ClearTextOnFocus: boolean,
    Placeholder: string,
    AllowEmpty: boolean,
    EmptyReset: string,
    Tooltip: string?,
    DisabledTooltip: string?,
    TooltipTable: Tooltip?,
    Callback: (Value: string) -> (),
    Changed: (Value: string) -> (),
    Disabled: boolean,
    Visible: boolean,
    Type: "Input",
    Holder: Frame,

    UpdateColors: (self: Input) -> (),
    OnChanged: (self: Input, Func: (Value: string) -> ()) -> (),
    SetValue: (self: Input, Text: string) -> (),
    SetDisabled: (self: Input, Disabled: boolean) -> (),
    SetVisible: (self: Input, Visible: boolean) -> (),
    SetText: (self: Input, Text: string) -> (),
    Destroy: (self: Input) -> (),
}

export type Slider = {
    Text: string,
    Value: number,
    Min: number,
    Max: number,
    Prefix: string,
    Suffix: string,
    Compact: boolean?,
    Rounding: number,
    Tooltip: string?,
    DisabledTooltip: string?,
    TooltipTable: Tooltip?,
    Callback: (Value: number) -> (),
    Changed: (Value: number) -> (),
    Disabled: boolean,
    Visible: boolean,
    AllowRightClickInput: boolean,
    Type: "Slider",
    Holder: Frame,

    UpdateColors: (self: Slider) -> (),
    Display: (self: Slider) -> (),
    OnChanged: (self: Slider, Func: (Value: number) -> ()) -> (),
    SetMax: (self: Slider, Value: number) -> (),
    SetMin: (self: Slider, Value: number) -> (),
    SetValue: (self: Slider, Value: number | string) -> (),
    SetDisabled: (self: Slider, Disabled: boolean) -> (),
    SetVisible: (self: Slider, Visible: boolean) -> (),
    SetAllowRightClickInput: (self: Slider, Allow: boolean) -> (),
    SetText: (self: Slider, Text: string) -> (),
    SetPrefix: (self: Slider, Prefix: string) -> (),
    SetSuffix: (self: Slider, Suffix: string) -> (),
    Destroy: (self: Slider) -> (),
}

export type Dropdown = {
    Connections: { RBXScriptConnection },
    Destroyed: boolean,

    Text: string?,
    Value: { [any]: boolean } | any,
    Values: { [any]: any },
    DisabledValues: { any },
    ValueImages: { [any]: string }?,
    Multi: boolean,
    DragSelect: boolean,
    KeepDisabledValuePosition: boolean,
    SpecialType: "Player" | "Team"?,
    ExcludeLocalPlayer: boolean?,
    EnablePlayerImages: boolean?,
    Tooltip: string?,
    DisabledTooltip: string?,
    TooltipTable: Tooltip?,
    Callback: (Value: any) -> (),
    Changed: (Value: any) -> (),
    Disabled: boolean,
    Visible: boolean,
    Type: "Dropdown",
    Menu: ContextMenu,
    Holder: Frame,
    Default: { any },
    DefaultValues: { [any]: any },

    RecalculateListSize: (self: Dropdown, Count: number?) -> (),
    UpdateColors: (self: Dropdown) -> (),
    Display: (self: Dropdown) -> (),
    OnChanged: (self: Dropdown, Func: (Value: any) -> ()) -> (),
    GetActiveValues: (self: Dropdown, ReturnCount: boolean?) -> { any } | number,
    RefreshPool: (self: Dropdown) -> (),
    BuildDropdownList: (self: Dropdown) -> (),
    RunChanged: (self: Dropdown) -> (),
    SetValue: (self: Dropdown, Value: any) -> (),
    SetValues: (self: Dropdown, Values: { [any]: any }) -> (),
    AddValues: (self: Dropdown, Values: { [any]: any } | string) -> (),
    SetDisabledValues: (self: Dropdown, DisabledValues: { any }) -> (),
    AddDisabledValues: (self: Dropdown, DisabledValues: { any } | string) -> (),
    SetValueImages: (self: Dropdown, ValueImages: { [any]: string }) -> (),
    AddValueImages: (self: Dropdown, ValueImages: { [any]: string }) -> (),
    SetDisabled: (self: Dropdown, Disabled: boolean) -> (),
    SetVisible: (self: Dropdown, Visible: boolean) -> (),
    SetText: (self: Dropdown, Text: string) -> (),
    SetDragSelect: (self: Dropdown, Value: boolean) -> (),
    Destroy: (self: Dropdown) -> (),
}

export type Viewport = {
    Object: BasePart | Model,
    Camera: Camera,
    Interactive: boolean,
    AutoFocus: boolean,
    Visible: boolean,
    Type: "Viewport",
    Holder: Frame,

    SetObject: (self: Viewport, Object: Instance, Clone: boolean?) -> (),
    SetHeight: (self: Viewport, Height: number) -> (),
    Focus: (self: Viewport) -> (),
    SetCamera: (self: Viewport, Camera: Camera) -> (),
    SetInteractive: (self: Viewport, Interactive: boolean) -> (),
    SetVisible: (self: Viewport, Visible: boolean) -> (),
    Destroy: (self: Viewport) -> (),
}

export type Image = {
    Image: string,
    Color: Color3,
    RectOffset: Vector2,
    RectSize: Vector2,
    Height: number,
    ScaleType: Enum.ScaleType,
    Transparency: number,
    Visible: boolean,
    Type: "Image",
    Holder: Frame,

    SetHeight: (self: Image, Height: number) -> (),
    SetImage: (self: Image, NewImage: string) -> (),
    SetColor: (self: Image, Color: Color3) -> (),
    SetRectOffset: (self: Image, RectOffset: Vector2) -> (),
    SetRectSize: (self: Image, RectSize: Vector2) -> (),
    SetScaleType: (self: Image, ScaleType: Enum.ScaleType) -> (),
    SetTransparency: (self: Image, Transparency: number) -> (),
    SetVisible: (self: Image, Visible: boolean) -> (),
    Destroy: (self: Image) -> (),
}

export type Video = {
    Video: string,
    Looped: boolean,
    Playing: boolean,
    Volume: number,
    Height: number,
    Visible: boolean,
    Type: "Video",
    Holder: Frame,
    VideoFrame: VideoFrame,

    SetHeight: (self: Video, Height: number) -> (),
    SetVideo: (self: Video, NewVideo: string) -> (),
    SetLooped: (self: Video, Looped: boolean) -> (),
    SetVolume: (self: Video, Volume: number) -> (),
    SetPlaying: (self: Video, Playing: boolean) -> (),
    Play: (self: Video) -> (),
    Pause: (self: Video) -> (),
    SetVisible: (self: Video, Visible: boolean) -> (),
    Destroy: (self: Video) -> (),
}

export type UIPassthrough = {
    Instance: GuiBase2d,
    Height: number,
    Visible: boolean,
    Type: "UIPassthrough",
    Holder: Frame,

    SetHeight: (self: UIPassthrough, Height: number) -> (),
    SetInstance: (self: UIPassthrough, Instance: GuiBase2d) -> (),
    SetVisible: (self: UIPassthrough, Visible: boolean) -> (),
    Destroy: (self: UIPassthrough) -> (),
}

export type Divider = {
    Type: "Divider",
    Holder: Frame,
    Parent: BaseGroupbox,
    Destroy: (self: Divider) -> (),
}

export type Element =
    Label
    | Button
    | Toggle
    | Input
    | Slider
    | Dropdown
    | Viewport
    | Image
    | Video
    | UIPassthrough
    | Divider
export type Option =
    Toggle
    | Input
    | Slider
    | Dropdown
    | Viewport
    | Image
    | Video
    | UIPassthrough
    | KeyPicker
    | ColorPicker

--// Container Types
export type BaseGroupbox = {
    AddDivider: (self: Groupbox, Info: (string | { Text: string?, Margin: number?, MarginTop: number?, MarginBottom: number? })?) -> (),
    AddLabel: (
        self: Groupbox,
        Info: { Text: string, DoesWrap: boolean?, Size: number?, Visible: boolean?, Idx: string? } | string,
        DoesWrap: boolean?,
        Idx: string?
    ) -> Label,
    AddButton: (self: Groupbox, Info: ButtonInfo | string, Func: (() -> ())?, Idx: string?) -> Button,
    AddCheckbox: (self: Groupbox, Idx: string, Info: ToggleInfo) -> Toggle,
    AddToggle: (self: Groupbox, Idx: string, Info: ToggleInfo) -> Toggle,
    AddInput: (self: Groupbox, Idx: string, Info: InputInfo) -> Input,
    AddSlider: (self: Groupbox, Idx: string, Info: SliderInfo) -> Slider,
    AddDropdown: (self: Groupbox, Idx: string, Info: DropdownInfo) -> Dropdown,
    AddViewport: (self: Groupbox, Idx: string, Info: ViewportInfo) -> Viewport,
    AddImage: (self: Groupbox, Idx: string, Info: ImageInfo) -> Image,
    AddVideo: (self: Groupbox, Idx: string, Info: VideoInfo) -> Video,
    AddUIPassthrough: (self: Groupbox, Idx: string, Info: UIPassthroughInfo) -> UIPassthrough,
    AddDependencyBox: (self: Groupbox) -> DependencyBox,
    AddDependencyGroupbox: (self: Groupbox) -> DependencyGroupbox,
    AddTabbox: (self: Groupbox, Info: { Name: string?, IconName: string? } | string) -> Tabbox,
    SetVisible: (self: Groupbox, Visible: boolean) -> (),
    Show: (self: Groupbox) -> (),
    Hide: (self: Groupbox) -> (),
}

export type DependencyBox = BaseGroupbox & {
    Visible: boolean,
    Dependencies: { [number]: { Element } },
    Holder: Frame,
    Container: Frame,
    Elements: { [number]: Element },
    DependencyBoxes: { [number]: DependencyBox },

    Resize: (self: DependencyBox) -> (),
    Update: (self: DependencyBox, CancelSearch: boolean?) -> (),
    SetupDependencies: (self: DependencyBox, Dependencies: { { Element } }) -> (),
}

export type DependencyGroupbox = BaseGroupbox & {
    Visible: boolean,
    Dependencies: { [number]: { Element } },
    BoxHolder: Frame,
    Holder: Frame,
    Container: Frame,
    Tab: Tab,
    Elements: { [number]: Element },
    DependencyBoxes: { [number]: DependencyBox },

    Resize: (self: DependencyGroupbox) -> (),
    Update: (self: DependencyGroupbox, CancelSearch: boolean?) -> (),
    SetupDependencies: (self: DependencyGroupbox, Dependencies: { { Element } }) -> (),
}

export type Groupbox = BaseGroupbox & {
    Name: string?,
    Description: string?,
    Visible: boolean,
    Collapsed: boolean,
    PoppedOut: boolean,
    PopOutEnabled: boolean,
    PopOutFloat: Frame?,
    PopOutPlaceholder: Frame?,
    PopOutMaxHeight: number?,
    PopOutWidth: number?,
    BoxHolder: Frame,
    Holder: Frame,
    Container: Frame,
    Tab: Tab,
    DependencyBoxes: { [number]: DependencyBox },
    Elements: { [number]: Element },

    Resize: (self: Groupbox) -> (),
    SetDescription: (self: Groupbox, Description: string?) -> (),
    SetCollapsed: (self: Groupbox, Collapsed: boolean) -> (),
    ToggleCollapsed: (self: Groupbox) -> (),
    SetPoppedOut: (self: Groupbox, Value: boolean, FloatPosition: UDim2?) -> (),
    TogglePoppedOut: (self: Groupbox) -> (),
    RefreshPopOutPlaceholder: (self: Groupbox) -> (),
    SetMaxPopOutHeight: (self: Groupbox, Height: number?) -> (),
    SetPopOutWidth: (self: Groupbox, Width: number?) -> (),
}

export type SubTab = BaseGroupbox & {
    Type: "SubTab",
    ButtonHolder: TextButton,
    Container: Frame,
    Tab: Tab,
    Tabbox: Tabbox,
    Elements: { [number]: Element },
    DependencyBoxes: { [number]: DependencyBox },

    Show: (self: SubTab) -> (),
    Hide: (self: SubTab) -> (),
    Resize: (self: SubTab) -> (),
}

export type Tabbox = {
    Type: "Tabbox",
    Visible: boolean,
    Destroyed: boolean,
    PoppedOut: boolean,
    PopOutEnabled: boolean,
    PopOutFloat: Frame?,
    PopOutPlaceholder: Frame?,
    PopOutMaxHeight: number?,
    PopOutWidth: number?,
    ActiveTab: SubTab?,
    BoxHolder: Frame,
    Holder: Frame,
    Tabs: { [string]: SubTab },
    ParentBox: (Groupbox | SubTab)?,

    AddTab: (self: Tabbox, Name: string, IconName: string?) -> (SubTab, number),
    Resize: (self: Tabbox) -> (),
    UpdateCorners: (self: Tabbox) -> (),
    SetPoppedOut: (self: Tabbox, Value: boolean, FloatPosition: UDim2?) -> (),
    TogglePoppedOut: (self: Tabbox) -> (),
    RefreshPopOutPlaceholder: (self: Tabbox) -> (),
    SetMaxPopOutHeight: (self: Tabbox, Height: number?) -> (),
    SetPopOutWidth: (self: Tabbox, Width: number?) -> (),
}

export type Tab = {
    Window: Window,
    Groupboxes: { [string]: Groupbox },
    Tabboxes: { [string]: Tabbox },
    DependencyGroupboxes: { [number]: DependencyGroupbox },
    Sides: { ScrollingFrame },
    WarningBox: { IsNormal: boolean, LockSize: boolean, Visible: boolean, Title: string, Text: string },
    Tooltip: string?,
    TooltipTable: Tooltip?,

    UpdateWarningBox: (
        self: Tab,
        Info: { IsNormal: boolean?, LockSize: boolean?, Visible: boolean?, Title: string?, Text: string? }
    ) -> (),
    Resize: (self: Tab, ResizeWarningBox: boolean?) -> (),
    AddGroupbox: (
        self: Tab,
        Info: {
            Side: number | string,
            Name: string,
            IconName: string?,
            Description: string?,
            Visible: boolean?,
            Collapsed: boolean?,
            DisableCollapsing: boolean?,
            PopOut: boolean?,
            MaxPopOutHeight: number?,
            PopOutWidth: number?,
        }
    ) -> Groupbox,
    AddLeftGroupbox: (
        self: Tab,
        Name: string,
        IconName: string?,
        Visible: boolean?,
        Collapsed: boolean?,
        DisableCollapsing: boolean?
    ) -> Groupbox,
    AddRightGroupbox: (
        self: Tab,
        Name: string,
        IconName: string?,
        Visible: boolean?,
        Collapsed: boolean?,
        DisableCollapsing: boolean?
    ) -> Groupbox,
    AddTabbox: (self: Tab, Info: { Side: number | string, Name: string?, PopOut: boolean?, MaxPopOutHeight: number?, PopOutWidth: number? }) -> Tabbox,
    AddLeftTabbox: (self: Tab, Name: string?) -> Tabbox,
    AddRightTabbox: (self: Tab, Name: string?) -> Tabbox,
    Hover: (self: Tab, Hovering: boolean) -> (),
    Show: (self: Tab) -> (),
    Hide: (self: Tab) -> (),
    SetVisible: (self: Tab, Visible: boolean) -> (),
    SetOrder: (self: Tab, Order: number) -> (),
    SetTooltip: (self: Tab, Text: string?) -> (),
}

export type KeyTab = BaseGroupbox & {
    Elements: { [any]: any },
    IsKeyTab: true,
    Window: Window,
    Container: ScrollingFrame,
    Tooltip: string?,
    TooltipTable: Tooltip?,

    AddKeyBox: (self: KeyTab, ExpectedKey: string?, Callback: (Success: boolean, Key: string) -> ()) -> (),
    Resize: (self: KeyTab) -> (),
    Hover: (self: KeyTab, Hovering: boolean) -> (),
    Show: (self: KeyTab) -> (),
    Hide: (self: KeyTab) -> (),
    SetVisible: (self: KeyTab, Visible: boolean) -> (),
    SetTooltip: (self: KeyTab, Text: string?) -> (),
}

export type LoadingErrorButtonInfo = {
    Title: string?,
    Variant: "Primary" | "Secondary" | "Destructive" | "Ghost"?,
    Callback: ((Loading) -> ())?,
}

export type LoadingSidebar = BaseGroupbox & {
    Elements: { [number]: Element },
    DependencyBoxes: { [number]: DependencyBox },
    Tabboxes: { [string]: Tabbox },
    BoxHolder: ScrollingFrame,
    Container: ScrollingFrame,
    Tab: {
        Elements: { [number]: Element },
        DependencyBoxes: { [number]: DependencyBox },
        DependencyGroupboxes: { [number]: DependencyGroupbox },
        Tabboxes: { [string]: Tabbox },
    },

    Resize: (self: LoadingSidebar) -> (),
}

export type Loading = {
    CurrentStep: number,
    TotalSteps: number,
    ShowSidebar: boolean,
    AutoResizeHeight: boolean,
    AlwaysOnTop: boolean,
    IsError: boolean,
    Destroyed: boolean,
    WindowWidth: number,
    WindowHeight: number,
    BaseWindowHeight: number,
    WindowErrorHeight: number,
    ContentWidth: number,
    SidebarWidth: number,
    ScreenGui: ScreenGui,
    Sidebar: LoadingSidebar,

    UpdateLayout: (self: Loading) -> (),
    RecalculateLoadingHeight: (self: Loading) -> (),
    SetMessage: (self: Loading, Text: string) -> (),
    SetDescription: (self: Loading, Text: string) -> (),
    SetLoadingIcon: (self: Loading, Icon: string | number) -> (),
    SetLoadingIconTweenTime: (self: Loading, TweenTime: number) -> (),
    SetLoadingIconColor: (self: Loading, Color: Color3) -> (),
    SetCurrentStep: (self: Loading, Step: number) -> (),
    SetTotalSteps: (self: Loading, Steps: number) -> (),
    SetWindowHeight: (self: Loading, Height: number) -> (),
    SetWindowWidth: (self: Loading, Width: number) -> (),
    SetContentWidth: (self: Loading, Width: number) -> (),
    SetSidebarWidth: (self: Loading, Width: number) -> (),
    ShowSidebarPage: (self: Loading, Bool: boolean) -> (),
    ShowErrorPage: (self: Loading, Enabled: boolean) -> (),
    RecalculateErrorHeight: (self: Loading) -> (),
    SetErrorMessage: (self: Loading, Text: string) -> (),
    SetErrorButtons: (self: Loading, Buttons: { [string]: LoadingErrorButtonInfo }) -> (),
    Destroy: (self: Loading) -> (),
    Continue: (self: Loading) -> (),
}

export type DialogButtonInfo = {
    Title: string,
    Variant: "Primary" | "Secondary" | "Destructive" | "Ghost"?,
    WaitTime: number?,
    Order: number?,
    Callback: ((Dialog) -> ())?,
}

export type Dialog = {
    SetTitle: (self: Dialog, Title: string) -> (),
    SetDescription: (self: Dialog, Description: string) -> (),
    AddFooterButton: (self: Dialog, ButtonIdx: string, ButtonInfo: DialogButtonInfo) -> (),
    RemoveFooterButton: (self: Dialog, ButtonIdx: string) -> (),
    SetButtonDisabled: (self: Dialog, ButtonIdx: string, Disabled: boolean) -> (),
    SetButtonOrder: (self: Dialog, ButtonIdx: string, Order: number) -> (),
    Dismiss: (self: Dialog) -> (),
}


export type Window = {
    AlwaysOnTop: boolean,
    Snapping: boolean?,
    IsSidebarCompacted: (self: Window) -> boolean,
    GetSidebarWidth: (self: Window) -> number,
    SetSidebarWidth: (self: Window, Width: number) -> (),
    SetCompact: (self: Window, State: boolean) -> (),
    ShowTabInfo: (self: Window, Name: string, Description: string) -> (),
    HideTabInfo: (self: Window) -> (),
    AddTab: (
        self: Window,
        Info: { Name: string, Icon: string?, Description: string?, Tooltip: string?, Order: number? } | string,
        Icon: string?,
        Description: string?,
        Order: number?
    ) -> Tab,
    AddKeyTab: (
        self: Window,
        Info: { Name: string, Icon: string?, Description: string?, Tooltip: string?, Order: number? } | string,
        Icon: string?,
        Description: string?
    ) -> KeyTab,
    AddDialog: (
        self: Window,
        Idx: string,
        Info: {
            Title: string,
            Description: string?,
            Icon: string?,
            TitleColor: Color3?,
            DescriptionColor: Color3?,
            AutoDismiss: boolean?,
            OutsideClickDismiss: boolean?,
            FooterButtons: { [string]: DialogButtonInfo }?,
        }
    ) -> Dialog,
    ChangeTitle: (self: Window, Title: string) -> (),
    SetBackgroundImage: (self: Window, Image: string) -> (),
    SetFooter: (self: Window, Footer: string) -> (),
    SetAlwaysOnTop: (self: Window, Enabled: boolean) -> (),
    SetCornerRadius: (self: Window, Radius: number) -> (),
    SetSnapping: (
        self: Window,
        Enabled: boolean,
        Distance: number?,
        Margin: number?,
        AvoidCoreGui: boolean?
    ) -> (),
    SetAnimations: (
        self: Window,
        Animations: { [string]: boolean }?,
        TabTransitionTime: number?,
        TabSwipeOffset: number?,
        TabSwipeFrom: ("left" | "right" | "top" | "bottom" | "auto" | string)?
    ) -> (),
    Toggle: (self: Window, Value: boolean?) -> (),
}

--// Main Library Type
export type Library = {
    -- Properties
    LocalPlayer: Player,
    DevicePlatform: Enum.Platform?,
    IsMobile: boolean,
    IsRobloxFocused: boolean,
    ScreenGui: ScreenGui?,
    Window: Window?,
    Floats: Frame?,
    Overlay: Frame?,
    SearchText: string,
    Searching: boolean,
    GlobalSearch: boolean,
    LastSearchTab: Tab?,
    ActiveTab: Tab?,
    ActiveLoading: Loading?,
    Tabs: { [string]: Tab | KeyTab },
    DependencyBoxes: { [number]: DependencyBox | DependencyGroupbox },
    KeybindFrame: Frame?,
    KeybindContainer: Frame?,
    KeybindToggles: { [number]: KeybindToggle },
    Notifications: { [GuiObject]: Notification },
    ToggleKeybind: Enum.KeyCode,
    TweenInfo: TweenInfo,
    NotifyTweenInfo: TweenInfo,
    TabTransitionInfo: TweenInfo,
    TabSwipeOffset: number,
    TabSwipeFrom: string,
    Animations: {
        ToggleWindow: boolean,
        TabSwitch: boolean,
        Groupbox: boolean,
        Dropdown: boolean,
        KeyPicker: boolean,
    },
    Toggled: boolean,
    Unloaded: boolean,
    Labels: { [string | number]: Label },
    Buttons: { [string | number]: Button | SubButton },
    Toggles: { [string | number]: Toggle },
    Options: { [string | number]: Option },
    NotifySide: "Right" | "Left",
    ShowCustomCursor: boolean,
    ForceCheckbox: boolean,
    ShowToggleFrameInKeybinds: boolean,
    NotifyOnError: boolean,
    CantDragForced: boolean,
    DraggableElements: { GuiObject },
    PopOutSnapDistance: number,
    PopOutDragThreshold: number,
    PopOutHoldTime: number,
    Signals: { [number]: RBXScriptConnection },
    UnloadSignals: { [number]: () -> () },
    MinSize: Vector2,
    DPIScale: number,
    CornerRadius: number,
    IsLightTheme: boolean,
    Scheme: Scheme,
    Registry: { [GuiObject]: { [string]: string | () -> Color3 } },
    Scales: { [GuiObject]: { [string]: any } },
    ScalesOffset: { [GuiObject]: { [string]: any } },
    CopiedColor: { Color3 | number }?,
    ImageManager: {
        AddAsset: (AssetName: string, RobloxAssetId: number, URL: string, ForceRedownload: boolean?) -> nil,
        GetAsset: (AssetName: string) -> string?,
        DownloadAsset: (AssetName: string, ForceRedownload: boolean?) -> nil,
    },

    -- Methods
    UpdateDependencyBoxes: (self: Library) -> (),
    UpdateSearch: (self: Library, SearchText: string) -> (),
    AddToRegistry: (self: Library, Instance: GuiObject, Properties: { [string]: string | () -> Color3 }) -> (),
    RemoveFromRegistry: (self: Library, Instance: GuiObject) -> (),
    UpdateColorsUsingRegistry: (self: Library) -> (),
    UpdateDPI: (self: Library, Instance: GuiObject, Properties: { [string]: any }) -> (),
    SetDPIScale: (self: Library, DPIScale: number) -> (),
    GiveSignal: (self: Library, Connection: RBXScriptConnection) -> RBXScriptConnection,
    GetIcon: (self: Library, IconName: string) -> Icon?,
    GetCustomIcon: (self: Library, IconName: string) -> Icon?,
    ApplyLucideIcon: (
        self: Library,
        ImageGui: ImageLabel | ImageButton,
        Icon: Icon,
        Rotation: number?
    ) -> (),
    Validate: (self: Library, Table: { [string]: any }, Template: { [string]: any }) -> { [string]: any },
    Cursor: {
        ChangeCrossColor: (self: Library, Color: Color3) -> (),
        ResetCross: (self: Library) -> (),
        ChangeIcon: (self: Library, ImageId: string) -> (),
        ChangeIconColor: (self: Library, Color: Color3) -> (),
        ChangeIconSize: (self: Library, Size: UDim2) -> (),
        ResetIcon: (self: Library) -> (),
    },
    ChangeCursorCrossColor: (self: Library, Color: Color3) -> (),
    ResetCursorCross: (self: Library) -> (),
    ChangeCursorIcon: (self: Library, ImageId: string) -> (),
    ChangeCursorIconColor: (self: Library, Color: Color3) -> (),
    ChangeCursorIconSize: (self: Library, Size: UDim2) -> (),
    ResetCursorIcon: (self: Library) -> (),
    GetBetterColor: (self: Library, Color: Color3, Add: number) -> Color3,
    GetLighterColor: (self: Library, Color: Color3) -> Color3,
    GetDarkerColor: (self: Library, Color: Color3) -> Color3,
    GetKeyString: (self: Library, KeyCode: Enum.KeyCode) -> string,
    GetTextBounds: (self: Library, Text: string, Font: Font, Size: number, Width: number?) -> (number, number),
    MouseIsOverFrame: (self: Library, Frame: GuiObject, Mouse: Vector2) -> boolean,
    IsInsideFrame: (self: Library, ParentFrame: GuiObject, Frame: GuiObject) -> boolean,
    SafeCallback: (self: Library, Func: (...any) -> ...any, ...any) -> ...any,
    MakeDraggable: (
        self: Library,
        UI: GuiObject,
        DragFrame: GuiObject,
        IgnoreToggled: boolean?,
        IsMainWindow: boolean?
    ) -> (),
    MakeResizable: (self: Library, UI: GuiObject, DragFrame: GuiObject, Callback: (() -> ())?) -> (),
    MakeCover: (self: Library, Holder: GuiObject, Place: string) -> Frame,
    MakeLine: (self: Library, Frame: GuiObject, Info: { AnchorPoint: Vector2?, Position: UDim2, Size: UDim2 }) -> Frame,
    AddOutline: (self: Library, Frame: GuiObject) -> Frame,
    AddBlank: (self: Library, Frame: GuiObject, Size: UDim2) -> (),
    MakeOutline: (self: Library, Frame: GuiObject, Corner: number?, ZIndex: number?) -> Frame,
    AddDraggableLabel: (
        self: Library,
        Text: string | { Text: string, Icon: string?, IconPosition: string? },
        Icon: string?,
        IconPosition: string?
    ) -> DraggableLabel,
    AddDraggableButton: (
        self: Library,
        Text: string
            | {
                Text: string,
                Callback: (() -> ())?,
                Func: (() -> ())?,
                ExcludeScaling: boolean?,
                ExcludeDragging: boolean?,
                Icon: string?,
                IconPosition: string?,
            },
        Func: ((DraggableButton) -> ())?,
        ExcludeScaling: boolean?,
        ExcludeDragging: boolean?,
        Icon: string?,
        IconPosition: string?
    ) -> DraggableButton,
    AddDraggableImageButton: (
        self: Library,
        Icon: string
            | {
                Icon: string,
                IconSize: number?,
                Callback: (() -> ())?,
                Func: (() -> ())?,
                ExcludeScaling: boolean?,
                ExcludeDragging: boolean?,
            },
        IconSize: number?,
        Func: ((DraggableImageButton) -> ())?,
        ExcludeScaling: boolean?,
        ExcludeDragging: boolean?
    ) -> DraggableImageButton,
    AddDraggableMenu: (self: Library, Name: string) -> (Frame, Frame),
    SetWatermarkVisibility: (self: Library, Visible: boolean) -> (),
    SetWatermark: (self: Library, Text: string) -> (),
    AddContextMenu: (
        self: Library,
        Holder: GuiObject,
        Size: UDim2 | () -> UDim2,
        Offset: { [number]: number } | () -> { [number]: number },
        List: number?,
        ActiveCallback: ((boolean) -> ())?
    ) -> ContextMenu,
    AddTooltip: (self: Library, InfoStr: string, DisabledInfoStr: string, HoverInstance: GuiObject) -> Tooltip,
    OnUnload: (self: Library, Callback: () -> ()) -> (),
    Unload: (self: Library) -> (),
    SetIconModule: (self: Library, module: any) -> (),
    SetFont: (self: Library, FontFace: Font | Enum.Font) -> (),
    SetNotifySide: (self: Library, Side: "Left" | "Right") -> (),
    UpdateNotificationPositions: (self: Library, Snap: boolean?) -> (),
    Notify: (
        self: Library,
        Info: {
            Title: string?,
            Description: string,
            Time: number?,
            SoundId: string | number?,
            Volume: number?,
            Steps: number?,
            Persist: boolean?,
            TitleColor: Color3?,
            DescriptionColor: Color3?,
            Icon: string | number?,
            IconColor: Color3 | string?,
            BigIcon: string?,
        } | string,
        Time: number?,
        SoundId: string | number?
    ) -> Notification,
    CreateLoading: (self: Library, LoadingInfo: LoadingInfo) -> Loading,
    CreateWindow: (
        self: Library,
        WindowInfo: {
            Title: string?,
            Footer: string?,
            Position: UDim2?,
            Size: UDim2?,
            Icon: string?,
            IconSize: UDim2?,
            BackgroundImage: string?,
            AutoShow: boolean?,
            Center: boolean?,
            Resizable: boolean?,
            DisableSearch: boolean?,
            SearchbarSize: UDim2?,
            GlobalSearch: boolean?,
            CornerRadius: number?,
            NotifySide: "Left" | "Right"?,
            ShowCustomCursor: boolean?,
            AlwaysOnTop: boolean?,
            Font: Font | Enum.Font?,
            ToggleKeybind: Enum.KeyCode?,
            ShowMobileButtons: boolean?,
            MobileButtonsSide: "Left" | "Right"?,
            UnlockMouseWhileOpen: boolean?,
            EnableSidebarResize: boolean?,
            EnableCompacting: boolean?,
            DisableCompactingSnap: boolean?,
            SidebarCompacted: boolean?,
            MinContainerWidth: number?,
            MinSidebarWidth: number?,
            SidebarCompactWidth: number?,
            SidebarCollapseThreshold: number?,
            CompactWidthActivation: number?,
            Snapping: boolean?,
            SnapDistance: number?,
            SnapMargin: number?,
            SnapAvoidCoreGui: boolean?,
            Animations: {
                ToggleWindow: boolean?,
                TabSwitch: boolean?,
                Groupbox: boolean?,
                Dropdown: boolean?,
                KeyPicker: boolean?,
            }?,
            TabTransitionTime: number?,
            TabSwipeOffset: number?,
            TabSwipeFrom: ("left" | "right" | "top" | "bottom" | "auto" | string)?,
            TabButtonsStyle: {
                Gap: number?,
                Padding: number?,
                CornerRadius: number?,
                Indicator: boolean?,
                IndicatorWidth: number?,
                IndicatorHeight: number?,
            }?,
        }
    ) -> Window,
    Toggle: (self: Library, Value: boolean?) -> (),
}

return nil
